development:
  cache:
    host: localhost
    port: 6380
    thread_safe: true
    zkservers: localhost:2181, localhost:2182, localhost:2183
    znode_path: /redis_failover/nodes
    db: 1

production:
  cache:
    thread_safe: true
    zkservers: localhost:2181, localhost:2182, localhost:2183
    znode_path: /redis_failover
    db: 0

test:
  hacache:
    zkservers: localhost:2181
    db: 8
    thread_safe: true
  myredisdb:
    db: 1
    host: localhost
    port: 6379
    thread_safe: true
  cache:
    db: 2
    host: localhost
    port: 6379
    thread_safe: true


